

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xdb?useUnicode=true&characterEncoding=UTF-8&useSSL=false&rewriteBatchedStatements=true
    username: x
    password: s123455

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
